data:
  raw: src/pipeline/data/student_features_dummy.csv
  processed: src/data/processed/student_features_processed.csv
outputs:
  model: models/dummy_model.pkl
  metrics: reports/metrics/pipeline_metrics.json
target: Performance
features:
  numeric: [age, hours_study]
  categorical: [gender, internet_access]
split:
  test_size: 0.2
  random_state: 42
model:
  name: random_forest
  params:
    n_estimators: 10
    max_depth: 5
data:
  raw: Equipo54_MLOps/src/data/student_entry_performance_modified.csv
  processed: Equipo54_MLOps/src/data/processed/student_performance_clean.csv
outputs:
  metrics: Equipo54_MLOps/reports/metrics/pipeline_metrics.json
